# Instruções

Esse documento é um [Jupyter notebook](http://jupyter.org/), um documento interativo que mistura texto (como esse), código (como abaixo), e o resultado de executar o código (números, texto, figuras, videos, etc).

O notebook te fornecerá exemplos interativos que trabalham o tema abordado.

As células com números ao lado, como `In [1]:`, são código [Python](https://www.python.org/). Algumas dessas células não produzem resultado e servem de preparação para os exemplos interativos. Outras, produzem gráficos interativos. **Você deve executar todas as células, uma de cada vez**, mesmo as que não produzem gráficos.

**Para executar uma célula**, clique em cima dela e aperte `SHIFT+ENTER` ou presione o botão de *Run* (<button class='fa fa-play icon-play btn btn-xs btn-default'></button>) na barra de ferramentas acima.  O foco (contorno verde ou cinza em torno da célula) deverá passar para a célula abaixo. Para rodá-la, aperte `SHIFT+ENTER` novamente e assim por diante. Você pode executar células de texto que não acontecerá nada.

# Por que usar Jupyter Notebook? 
Veja o artigo [Interactive notebooks: Sharing the code](http://www.nature.com/polopoly_fs/1.16261!/menu/main/topColumns/topLeftColumn/pdf/515151a.pdf) da revista nature

#### Autor:
* Dr. Oscar Fabian Mojica Ladino ([@ofmla](https://github.com/ofmla))

# Python

Python é uma linguagem de programação de alto nível, dinâmica, interpretada, modular, multiplataforma e orientada a objetos. 

Objetivo geral: análise de dados, desenvolvimento web, GUIs, sistemas em tempo real, etc.

Atualmente a linguagem de programação que mais cresce.

Em desenvolvimento ativo: Python 3.9 lançado em Outubro de 2020

- Fácil de começar
    - Maior produtividade no desenvolvimento, especialmente no início do projeto
    - Da ideia ao código funcional em pouco tempo
    - Ótimo para testar ideias e experimentos rápidos
- Biblioteca padrão abrangente: coleções, algoritmos, I/O ...
    - Python foi projetado para ser uma linguagem pequena com uma grande biblioteca padrão
- Ecossistema de bibliotecas incrível
    - Computação numérica e científica: numpy, scipy, sympy, xarray ...
    - Visualização: matplotlib, plotly, bokeh ...
    - Tabelas e séries temporais: pandas
    - _Machine Learning_: scikit-learn, tensorflow, keras, pytorch
- Gerenciamento de pacote padrão
    - Extremamente fácil de configurar o ambiente de desenvolvimento e instalar pacotes

Python é uma linguagem de sintaxe relativamente simples e de fácil compreensão que tem sido cada vez mais usada por engenheiros e cientistas. Python oferece uma gama completa de recursos de linguagem de programação e há uma vasta quantidade de pacotes para cálculos científicos e de engenharia. Existem inumeros recursos na internet onde você pode ir para obter mais informações sobre programação em Python, p.ex. [ Software-Carpentry Lessons](https://software-carpentry.org/lessons/)

## Numpy

[Numpy](https://numpy.org/) é a biblioteca central para computação científica em Python. A ideia fundamental do NumPy é o suporte a _arrays_ multidimensionais ferramentas para trabalhar com esses _arrays_.


## _Setup_

Rode as células abaixo para carregar os módulos necessários para essa prática.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0]


'1.20.1'

### _Arrays_

Um numpy _array_ é uma grade de valores, todos do mesmo tipo, e é indexado por uma tupla de inteiros não negativos. O número de dimensões é o _rank_ da matriz; a forma do _array_ é uma tupla de inteiros fornecendo o tamanho da matriz ao longo de cada dimensão.

Podemos inicializar numpy _arrays_ a partir de listas Python aninhadas e acessar elementos usando colchetes:

In [2]:
a = np.array([1, 2, 3])   # Cria um array de rank 1 
print(type(a))            # Printa "<class 'numpy.ndarray'>"
print(a.shape)            # Printa "(3,)"
print(a[0], a[1], a[2])   # Printa "1 2 3"
a[0] = 5                  # Muda um elemento do array
print(a)                  # Printa "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Cria um array de rank 2 
print(b.shape)                     # Printa "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Printa "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


O Numpy também oferece muitas funções para criar _arrays_:

In [3]:
import numpy as np

a = np.zeros((2,2))   # Cria um array zerado
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Cria um array com todos os elemntos iguais a 1
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Cria um array com todos os elementos sendo um valor constate
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Cria uma matriz identidade 2x2
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Cria um array preenchido com valores aleatorios
print(e)                     

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.23062439 0.70677808]
 [0.12674632 0.07819914]]


## _Slicing arrays_

__Fatiar__: _Arrays_ multidimensionais podem ser fatiados. 

In [4]:
# Cria o seguinte array de rank 2 e shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use o fatiamento para obter um subarray consistendo das primeiras 2 filas
# e colunas 1 e 2; b fica da seguinte forma com shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# Uma fatia de um array é uma visualização dos mesmos dados, portanto, modificá-la
# irá modificar o array original
print(a[0, 1])   # Printa "2"
b[0, 0] = 77     # b[0, 0] são os mesmos dados que a[0, 1]
print(a[0, 1])   # Printa "77"

2
77


In [5]:
# Cria de novo o array 'a' de rank 2 e shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Duas maneiras de acessar os dados na linha do meio do array.
# Misturar indexação de inteiro com fatias produz uma matriz de rank inferior,
# enquanto usando apenas fatias produz uma matriz do mesm rank que o
# array original:

row_r1 = a[1, :]    # vista da segunda fila de a de rank 1
row_r2 = a[1:2, :]  # vista da segunda fila de a de rank 2
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# A mesma distinção pode ser feita ao acessar colunas de um array
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [6]:
# Crie uma array novo a partir da qual selecionaremos os elementos
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # printa "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Crie uma série de índices
b = np.array([0, 2, 0, 1])

# Selecione um elemento de cada linha de a usando os índices em b
print(a[np.arange(4), b])  # Printa "[ 1  6  7 11]"

# Transformar um elemento de cada linha de a usando os índices em b
a[np.arange(4), b] += 10

print(a)  # printa "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [7]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Encontra os elementos de a que são maiores que 2;
                     # isso retorna um numpy array de Booleanos da mesmo
                     # forma de a, onde cada elemento de bool_idx informa
                     # se esse elemento de a é> 2

print(bool_idx)      # Printa "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"
        
# Usamos indexação do array booleano para construir um array de rank 1
# consistindo nos elementos de a correspondente aos valores verdadeiros
# de bool_idx

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Printa "[3 4 5 6]"

# Podemos fazer tudo isso em uma única declaração concisa::
print(a[a > 2])     # Printa "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Matemática em _arrays_

Funções matemáticas básicas operam elemento a elemento em _arrays_ e estão disponíveis como operadores e como funções no módulo numpy:

In [8]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Soma elemento a elemento; ambos produzem o array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Substração elemento a elemento; ambos produzem o array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Produto elemento a elemento; ambos produzem o array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Divisão elemento a elemento; ambos produzem o array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Raiz quadrada elemento a elemento; ambos produzem o array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


A função ```dot``` é usada para calcular produtos internos de vetores, para multiplicar um vetor por uma matriz e para multiplicar matrizes. ```dot``` está disponível como uma função no módulo numpy e como um método de instância de objetos array:

In [9]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# produto interno de vetores; ambos produzem 219
print(v.dot(w))
print(np.dot(v, w))

# produto Matriz/vetor; ambos produzem um array de rank 1 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# produto Matrix/matrix ; ambos produzem array de rank 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


O Numpy fornece muitas funções úteis para realizar cálculos em matrizes; um dos mais úteis é a ```sum```:

In [10]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Computa a soma de todos os elementos; printa "10"
print(np.sum(x, axis=0))  # Computa a soma de cada coluna; prints "[4 6]"
print(np.sum(x, axis=1))  # Computa a soma de cada fila; prints "[3 7]"

10
[4 6]
[3 7]


Você pode encontrar a lista completa de funções matemáticas fornecidas por numpy na [documentação](https://numpy.org/doc/stable/reference/routines.math.html).

Além de computar funções matemáticas usando _arrays_, frequentemente precisamos mudar (_reshaping_) a forma ou manipular dados em _arrays_. O exemplo mais simples desse tipo de operação é a transposição de uma matriz; para transpor uma matriz, basta usar o atributo ```T``` de um objeto de matriz:


In [11]:
x = np.array([[1,2], [3,4]])
print(x)    # Printa "[[1 2]
            #          [3 4]]"
print(x.T)  # Printa "[[1 3]
            #          [2 4]]"

# Observe que a transposição de um array de rank 1 não faz nada::
v = np.array([1,2,3])
print(v)    # Printa "[1 2 3]"
print(v.T)  # Printa "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


O Numpy fornece muito mais funções para manipular _arrays_; você pode ver a lista completa na [documentação](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).